spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sof3011_lap
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.hbm2ddl.auto: update
    show-sql: true
introspection:
  enabled: true
  endpoint: /graphql
